# Render.com deployment configuration
services:
  - type: web
    name: tictactoe-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --bind 0.0.0.0:$PORT --timeout 30
    envVars:
      - key: FLASK_ENV
        value: production
